
<body class="color-change-2x">


<div class="bloxx">
    <div class="boxx">
        <h1 class="mb-2 mt-2 tracking-in-expand"><span style="color: cadetblue;">ADMIN</span> E-Chin</h1>
        
        <hr>
        <div class="mb-2">
            <input type="text" class="form-control" placeholder="Username">
        </div>
        <div class="mb-2">
            <input type="text" class="form-control" placeholder="Password">
        </div>
        <hr>
        <div class="btx">Login</div>
    </div>
</div>

</body>
<footer class="page-footer" style="position: absolute;width: 100%;bottom: 0px;">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-sm-6">
                    <p>Copyright <script>document.write(new Date().getFullYear())</script> &copy; <a href="#" target="_blank">E-Chin</a></p>
                </div>
                <div class="col-sm-6">
                    <div class="socials">
                        <a class="social-item" href="javascript:void(0)" style="padding-top: 9px;"><i class="ti-facebook"></i></a>
                        <a class="social-item" href="javascript:void(0)" style="padding-top: 9px;"><i class="ti-github"></i></a>
                        <a class="social-item" href="javascript:void(0)" style="padding-top: 9px;"><i class="ti-twitter"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </footer> 
<style>
    input{
        text-align: center;
    }
    .btx{
        background-color: darkseagreen;
        padding: 12px;
        margin: 16px 0px;
    }
    body,h1,h2,h3,h4,h5,div,span{
        font-family: 'Playfair Display', serif;
    }
    .btx:hover{
        background-color: #f2f2f2;
        padding: 12px;
        margin: 16px 0px;
    }
    .spanx{
        background-color: red;
        color: white;
        padding: 8px 17px;
        box-shadow: 0px 2px 10px -5px #000;
    }
    body{
        background-color: #9FE2BF;
    }
    .bloxx{
        padding-top: 180px;
        text-align: center;
    }
    @media only screen and (max-width: 600px) {
        .bloxx{
            padding-top: 90px;
            text-align: center;
            margin: 20px;
        }
    }
    .boxx{
        background-color: #ddd;
        width: 400px;
        margin: auto;
        max-width: 100%;
        padding: 15px 20px;
        border-radius: 10px;
        box-shadow: 0px 2px 10px -5px;
    }
    .tracking-in-expand {
	-webkit-animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
	        animation: tracking-in-expand 0.7s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
    }
    /* ----------------------------------------------
    * Generated by Animista on 2023-9-26 10:1:26
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

    /**
    * ----------------------------------------
    * animation tracking-in-expand
    * ----------------------------------------
    */
    @-webkit-keyframes tracking-in-expand {
    0% {
        letter-spacing: -0.5em;
        opacity: 0;
    }
    40% {
        opacity: 0.6;
    }
    100% {
        opacity: 1;
    }
    }
    @keyframes tracking-in-expand {
    0% {
        letter-spacing: -0.5em;
        opacity: 0;
    }
    40% {
        opacity: 0.6;
    }
    100% {
        opacity: 1;
    }
    }

    .color-change-2x {
	-webkit-animation: color-change-2x 2s linear infinite alternate both;
	        animation: color-change-2x 2s linear infinite alternate both;
    }
  
    @-webkit-keyframes color-change-2x {
    0% {
        background: #9FE2BF;
    }
    100% {
        background: #2ECC71;
    }
    }
    @keyframes color-change-2x {
    0% {
        background: #9FE2BF;
    }
    100% {
        background: #2ECC71;
    }
    }

</style>